name: RunnerNba

on:
  push:
    branches:
      - main

jobs:
  your_job_name:
    runs-on: ubuntu-latest

    env:
      GSHEET_NBA_MAKU_CREDENTIALS: ${{ secrets.GSHEET_NBA_MAKU_CREDENTIALS }}
      GSHEET_NBA_MAKU_FOLDER_ID: ${{ secrets.GSHEET_NBA_MAKU_FOLDER_ID }}
      FORMAT_OUTPUT_TYPE: ${{ vars.FORMAT_OUTPUT_TYPE }}
      FILENAME_OUTPUT: ${{ vars.FILENAME_OUTPUT }}
      GSHEET_NBA_MAKU_TIME_DELAY: ${{ vars.GSHEET_NBA_MAKU_TIME_DELAY }}
      ONEDRIVE_EXCEL_NBA_PATH: ${{ vars.ONEDRIVE_EXCEL_NBA_PATH }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set up PowerShell
        run: |
          $env:Path += ";${env:ProgramFiles}\PowerShell\7"
          echo "##vso[task.prependpath]${env:ProgramFiles}\PowerShell\7"
          pwsh -c "Set-ExecutionPolicy -Scope CurrentUser Unrestricted"      
      
      - name: Wait for 30 seconds
        run: |
          echo "Waiting for 30 seconds..."
          sleep 30
  
      - name: Run PowerShell Script
        run: |
          pwsh -File UpdateNbaExcel.ps1
