name: RunnerNba

on:
  push:
    branches:
      - main

jobs:
  your_job_name:
    runs-on: windows-latest

    env:
      GSHEET_NBA_MAKU_CREDENTIALS: ${{ secrets.GSHEET_NBA_MAKU_CREDENTIALS }}
      GSHEET_NBA_MAKU_FOLDER_ID: ${{ secrets.GSHEET_NBA_MAKU_FOLDER_ID }}
      FORMAT_OUTPUT_TYPE: ${{ vars.FORMAT_OUTPUT_TYPE }}
      FILENAME_OUTPUT: ${{ vars.FILENAME_OUTPUT }}
      GSHEET_NBA_MAKU_TIME_DELAY: ${{ vars.GSHEET_NBA_MAKU_TIME_DELAY }}
      ONEDRIVE_EXCEL_NBA_PATH: ${{ vars.ONEDRIVE_EXCEL_NBA_PATH }}

    steps:
      - name: Set Up PowerShell
        uses: microsoft/setup-powershell@v1      
  
      - name: Run PowerShell Script
        run: |
          pwsh -ExecutionPolicy Bypass -File UpdateNbaExcel.ps1
